### ISSUE TITLE
Windows convention for SDR brightness is 80 nits, not 100 nit

### ISSUE THREAD

**Issue by dimula73** [sobotka/krita-hdr-ocio#1]
When converting HDR content to an SDR surface Widnows uses a convention that SDR's diffuse white point is 80 nits. So it clips all the colors that are above this point. The current version of the config uses 100nits point instead, which gives inconsistent results on Windows. 

This patch fixes the issue:
https://phabricator.kde.org/T9256#173994

**Comment by sobotka** [comment]
Patch is an epic failure.

**Comment by dimula73** [comment]
Hi, @sobotka!

Could you propose any way how to fix the original bug of the current version of the config?

Here is the original sRGB file:
![test_gray](https://user-images.githubusercontent.com/454873/51431901-69cc6b80-1c40-11e9-9d24-8a299c1b9366.png)

Here is how it is rendered on an p2020-pq surface and then converted back into SDR by Windows with the current version of the config (please note that the range is clipped by level 230):
![gray_rendered_100nits](https://user-images.githubusercontent.com/454873/51431907-88326700-1c40-11e9-80ea-f46aea17919d.png)

Here is how it is rendered with the patch I proposed (the gradient takes the full 8-bit range):
![gray_rendered_80nits](https://user-images.githubusercontent.com/454873/51431913-b152f780-1c40-11e9-8752-09d6637e554f.png)

The gradient is not ideal (looks like some rounding errors happen), but I'm not sure if it is just quantization errors or something. And it fixes the bug.

Speaking truly, I don't know where you took this 100nits value from. [sRGB standard](www.color.org/srgb.pdf) says about 80 nits, and nothing about 100 nits.


PS:
Here are the settings I use for testing:
![image](https://user-images.githubusercontent.com/454873/51432016-207d1b80-1c42-11e9-9077-6b5dc100289a.png)

**Comment by sobotka** [comment]
> Could you propose any way how to fix the original bug of the current version of the config?

Is it a bug?

> Speaking truly, I don't know where you took this 100nits value from. sRGB standard says about 80 nits, and nothing about 100 nits.

That’s spoken from someone who doesn’t have a clue what the 80 nits represents nor it’s relationship to an encoding.

I’m not explaining it again.

**Comment by dimula73** [comment]
> > Could you propose any way how to fix the original bug of the current version of the config?
> Is it a bug?

Yes, it renders stuff incorrectly on an SDR display

**Comment by therahedwig** [comment]
Hey, Dmitry, I cannot reproduce the result you're getting with an SDR device.

What I've done:

1. Get an SDR device running windows 10(A Toshiba Satelitte laptop)
2. Install the version of Krita you gave me this afternoon.
3. Ensure display is using Angle: done!
4. Download this repo's ocio config and set LUT docker to use it.
5. Create a black to white gradient in 8bit with the default sRGB profile, 256 steps wide.
6. Set following values:

Input CS: BT.709 E2.2 Nonlinear.
Display D: 100 nit REC.709 E2.2 Nonlinear(because this is the interpretation closest to this screen's properties.)
View: 2.2 transfer.
Look: none
Components: all channels
Exposure: 0
Gamma: 1

When I use the exact settings you are using as according to the screenshot(which are funny, because, why do you have the bt.2020st.2084 display selected when you are looking through an sRGB display at the colors?) Then my white looks like middle gray(so I cannot reproduce a situation where white is clamped to 230). Presumably these settings are only intended for monitors that aim to show bt2020?

I get the exact same results on my Linux device too, so maybe there's something funny going on with your computer?

EDIT screenshot:
https://pasteboard.co/HXmEK1m.png

**Comment by dimula73** [comment]
> 3. Ensure display is using Angle: done!
> (which are funny, because, why do you have the bt.2020st.2084 display selected when you are looking through an sRGB display at the colors?)

After point 3 you should have selected "Surface type" in the settings to Rec2020PQ and restart Krita. After that, you will have to select Rec2020 configuration in OCIO docker.

Right now, in your configuration there is no conversion to Rec2020PQ happens, therefore you don't see the problem :)

**Comment by therahedwig** [comment]
I am unable to get Rec2020PQ as prefered output format, Rec. 709 linear(16bit) does work, and I get the same results as sRGB(8bit)... Is the option only available on the black monster?

**Comment by dimula73** [comment]
The option should be available everywhere. This is how it looks on my PC:

![image](https://user-images.githubusercontent.com/454873/51444499-6e108b80-1d09-11e9-884f-38422aa130e8.png)

The main trick is that you should restart Krita after choosing the the preferred format. And you should have version 0.7, not earlier.
